[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "AioKafkaEngine"
version = "0.0.2"
authors = [
  { name="RusticPotatos", email="author@example.com" },
]
description = "Wrapper around aio-kafka to use and receive via a asyncio queue"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/RusticPotatos/AioKafkaEngine"
"Bug Tracker" = "https://github.com/RusticPotatos/AioKafkaEngine/issues"